# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kafkamessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosts', models.CharField(max_length=128, verbose_name='主机名')),
                ('theme', models.CharField(max_length=128, verbose_name='kafka主题')),
                ('code', models.CharField(max_length=128, verbose_name='kafkacode')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'kafka相关',
                'verbose_name_plural': 'kafka相关',
            },
        ),
    ]
